require('dotenv').config();

module.exports = {
    app_name:'Bagzag',
    app_url:'/v1/user',
    API_KEY: process.env.API_KEY,  
    ENCRYPTION_KEY: 'cryptlib.getHashSha256("238a97b8c6cb73c22463e025bbefd49",32)' , 
    ENCRYPTION_IV: "e025bbefd4941de2", 
    port_base_url:"http://localhost:8080/",
    mailer_email:'paramshah2606@gmail.com',               
    mailer_password:'giao hddk whhd agcc',
    from_email:"paramshah2606@gmail.com",
    PORT:process.env.PORT,
    DB_Password:process.env.DB_Password,
    DB_Database:process.env.DB_Database,
    DB_User:process.env.DB_User,
    DB_Host:process.env.DB_Host,
    KEY:process.env.KEY,
    IV:process.env.IV,
    JWT_SECRET:process.env.JWT_SECRET,
    ACCOUNT_SID_TWILIO:process.env.ACCOUNT_SID_TWILIO,
    AUTH_TOKEN_TWILIO:process.env.AUTH_TOKEN_TWILIO,
    cloud_name: process.env.CLOUD_NAME,
    cloud_api_key: process.env.CLOUD_API_KEY,
    cloud_api_secret: process.env.CLOUD_API_SECRET,
    open_ai_key:process.env.OPEN_AI_KEY,
    GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET:process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI:process.env.GOOGLE_REDIRECT_URI
  };